[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "django-pgallery"
description = "Photo gallery app for PostgreSQL and Django."
readme = "README.rst"
requires-python = ">=3.9"
authors = [{name="Zbigniew Siciarz", email="zbigniew@siciarz.net"}]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Framework :: Django :: 5.0",
    "Framework :: Django :: 5.1",
    "Topic :: Utilities",
]
dependencies = [
    "Django>=4.2,<6.0",
    "Pillow>=10",
    "psycopg2>=2.8",
    "django-markitup>=4.0",
    "django-model-utils>=5.0",
]
dynamic = ["version"]

[project.urls]
source = "https://github.com/zsiciarz/django-pgallery"

[tool.setuptools.dynamic]
version = {attr = "pgallery.__version__"}
