[tox]
envlist = py{39,310,311,312}-dj42, py{310,311,312}-dj{50,51}, py312-coverage

[testenv]
deps=
    dj42: Django>=4.2,<5.0
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2
commands=
    make test
allowlist_externals=make
set_env =
    UV_PROJECT_ENVIRONMENT={envdir}
passenv=
    LANG
    DATABASE_USER
    DATABASE_PASSWORD

[py312-dj51:py312-coverage]
commands=
    make coverage
deps=
    {[py312-dj51]deps}
    coverage==7.6.2

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
