name: django-pgallery build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
       - echo "Triggered from ${{ github.ref }}"
       - echo "Running Python ${{ matrix.python-version }}"
